### ISSUE TITLE
Instance Slider doens't work on Glyphs 3

### ISSUE THREAD

**Issue by weiweihuanghuang** [Tosche/Glyphs-Scripts#23]
3.0.3 (3081)
```
Traceback (most recent call last):
  File "Instance Slider.py", line 11
    from robofab.interface.all.dialogs import AskString
  File "dialogs.py", line 136
    print "robofab.interface.all __init__ - finding out where we were."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("robofab.interface.all __init__ - finding out where we were.")?
```
Robofab issue? @schriftgestalt

**Comment by Tosche** [comment]
No, this one is just missing parenthesis necessary in Python 3. I'll work on it.

**Comment by Tosche** [comment]
Updated the script. Does it work for you? (it now does on mine)

**Comment by weiweihuanghuang** [comment]
Works! I had to update robofab dialogs.py
