### ISSUE TITLE
Duplicate Glyph with Component error

### ISSUE THREAD

**Issue by synthview** [Tosche/Glyphs-Scripts#30]
Hello,
Duplicate Glyph with Component.py
gives me this error on Glyphs 3.2 (3245).  

I was trying to apply it to the glyphs:  copyright registered published 

Traceback (most recent call last):
  File "Duplicate Glyph with Component.py", line 39
    newSuffix = findSuffix( newGlyphNameBase )
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Duplicate Glyph with Component.py", line 27, in findSuffix
    if f.glyphs[ glyphName + suffix ] == None:
                 ~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by Tosche** [comment]
Thanks for the report. I've pushed the update that hopefully fixes the issue.

**Comment by synthview** [comment]
no error in macro window but nothing happens

**Comment by Tosche** [comment]
Updated the script. Now it should be working (better).

**Comment by synthview** [comment]
it works now, thanks!
